### ISSUE TITLE
Before Visit on September 21st

### ISSUE THREAD

**Issue by diego-ons** [tech-acs/crvsreportpackage#51]
## Description

Ahead of the visit starting in September 21st September there are some updates that are necessary for the codebase.

Package updates:

- [ ] Data Cleaning update (#50)
- [ ] Sorting of tables by value (#45)
- [ ] Add a vignette or two for the delivery guidance (@beardl-ons should have a prototype of this available)
- [ ] Pin down function naming convention (#13)
- [ ] Review tables used and update where necessary (#43 #38 #36 #35 )
- [ ] Add some error handling for tables (#9)
- [ ] Bring in information on set-up for delegates (https://rcatlord.github.io/vstraining/materials/setup.html)

Pre-visit work:

- [ ] Generate a synthetic data/some basic data ingestion script following the information provided.
- [ ] Identify what tables are available from the package and which need to be bespoke based on desired tables provided.
- [ ] Ensure all delegates have working R and R studio installations (with the `crvsreportpackage` installed).
- [ ] Establish path desired by country to deal with codebase moving forward (do they have a GitHub/version control solution?).
- [ ] Establish how the data will be shared/used by delegates during the week.
- [ ] Open conversation of next steps after visit to set path for CRVS report publication (and table sharing across government).

**Comment by jeroenminderman** [comment]
Potential additional (technical) items - happy to set up specific issues but thought I'd check first @tbelay @gulilattesfaye @diego-ons @rcatlord: 
- [x] Based on earlier in-country delivery, there seemed to be an issue with the generation of **fertility** age groups (e.g. [here](https://github.com/tech-acs/crvsreportpackage/blob/main/R/construct_age_group.R) or [here](https://github.com/tech-acs/crvsreportpackage/blob/main/R/derive_agegroup.R), vs @beardl-ons's [original](https://github.com/tech-acs/crvsreportpackage/blob/main/R/derive_agegroup.R)). This may just have been that there was an error in which function was being used in processing steps, but worth checking expected process / specifically required groupings? 
- [x] ~~Most tests of function generators currently implemented are limited to testing e.g. numbers of columns in outputs, as opposed to correct derivation/calculations. Would it be better to ensure all these use *externally sourced* data inputs (e.g. like available [here](https://github.com/tech-acs/crvsreportpackage/tree/main/inst/extdata), as opposed to "hard coded" toy examples - so an approach like [here](https://github.com/tech-acs/crvsreportpackage/blob/main/tests/testthat/test-create_table_4_1.R) vs [here](https://github.com/tech-acs/crvsreportpackage/blob/main/tests/testthat/test-create_table_4_3.R)), and **explicitly test against expected output tables**? This would be especially important if [error handling / partial table building](https://github.com/tech-acs/crvsreportpackage/issues/9) is implemented, and gives a good way of standardising test data and expandability of tests.~~ **suggested implementation as per [test-create_table_5_1.R](https://github.com/tech-acs/crvsreportpackage/blob/main/tests/testthat/test-create_table_5_1.R)**
- [ ] For #50, would again using the provided sample (dummy) data be a way to provide comprehensive tests for this, particularly if we include some common/likely data issues in that data set?
